const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "09160885836";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "typing" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_16_21_05_18_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTYzLFxuICAgICAgICA0OSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxNjgsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMjM4LFxuICAgICAgICAxODQsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMjM2LFxuICAgICAgICAxNSxcbiAgICAgICAgMjI4LFxuICAgICAgICA0OSxcbiAgICAgICAgMjE2LFxuICAgICAgICAxNDQsXG4gICAgICAgIDU0LFxuICAgICAgICAyNDksXG4gICAgICAgIDE2LFxuICAgICAgICA1LFxuICAgICAgICAzNixcbiAgICAgICAgMTg3LFxuICAgICAgICAyMzUsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMjE2LFxuICAgICAgICAxNTEsXG4gICAgICAgIDk5LFxuICAgICAgICAyNTAsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTMsXG4gICAgICAgIDE1MixcbiAgICAgICAgNjVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTMzLFxuICAgICAgICAxLFxuICAgICAgICA4MyxcbiAgICAgICAgOTIsXG4gICAgICAgIDIwOSxcbiAgICAgICAgNzgsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjAxLFxuICAgICAgICAxOTMsXG4gICAgICAgIDE5LFxuICAgICAgICA2OCxcbiAgICAgICAgNzcsXG4gICAgICAgIDYxLFxuICAgICAgICA2NSxcbiAgICAgICAgMTEwLFxuICAgICAgICAxMzksXG4gICAgICAgIDEzLFxuICAgICAgICAxOSxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyMjEsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMTExLFxuICAgICAgICAyNCxcbiAgICAgICAgMTYxLFxuICAgICAgICAyMSxcbiAgICAgICAgOCxcbiAgICAgICAgMTE1LFxuICAgICAgICA2MSxcbiAgICAgICAgMjQzLFxuICAgICAgICAxNDQsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTk2LFxuICAgICAgICA0OCxcbiAgICAgICAgMjMwLFxuICAgICAgICA2NyxcbiAgICAgICAgNzksXG4gICAgICAgIDE5NixcbiAgICAgICAgODUsXG4gICAgICAgIDgxLFxuICAgICAgICA2OSxcbiAgICAgICAgNTQsXG4gICAgICAgIDM4LFxuICAgICAgICA2NyxcbiAgICAgICAgMTc5LFxuICAgICAgICAxMTAsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMjE5LFxuICAgICAgICAzNyxcbiAgICAgICAgNTMsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTk5LFxuICAgICAgICA4NSxcbiAgICAgICAgOTgsXG4gICAgICAgIDE4MSxcbiAgICAgICAgNTUsXG4gICAgICAgIDAsXG4gICAgICAgIDM5LFxuICAgICAgICAxMyxcbiAgICAgICAgOSxcbiAgICAgICAgMTk1LFxuICAgICAgICAyNDUsXG4gICAgICAgIDEyNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA5MyxcbiAgICAgICAgMTM5LFxuICAgICAgICAxNzEsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMSxcbiAgICAgICAgMjM0LFxuICAgICAgICAxMzksXG4gICAgICAgIDEwNCxcbiAgICAgICAgNjQsXG4gICAgICAgIDY2LFxuICAgICAgICAyNDMsXG4gICAgICAgIDExLFxuICAgICAgICAxNzQsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTY2LFxuICAgICAgICA3MixcbiAgICAgICAgNjYsXG4gICAgICAgIDIzOSxcbiAgICAgICAgNzQsXG4gICAgICAgIDQsXG4gICAgICAgIDE5LFxuICAgICAgICAxNDUsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTAyLFxuICAgICAgICAxNzcsXG4gICAgICAgIDE4NSxcbiAgICAgICAgNjgsXG4gICAgICAgIDYsXG4gICAgICAgIDU1LFxuICAgICAgICAxOTksXG4gICAgICAgIDEyMyxcbiAgICAgICAgMThcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIwMCxcbiAgICAgICAgNTYsXG4gICAgICAgIDUsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTI2LFxuICAgICAgICAxOTAsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTM5LFxuICAgICAgICAyNTAsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTIwLFxuICAgICAgICA3NSxcbiAgICAgICAgMjIsXG4gICAgICAgIDcwLFxuICAgICAgICA0MyxcbiAgICAgICAgMjE3LFxuICAgICAgICAxNjMsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTQ4LFxuICAgICAgICA4NyxcbiAgICAgICAgMjE4LFxuICAgICAgICAxOTUsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTQ4LFxuICAgICAgICAyNTMsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjQyLFxuICAgICAgICAxNzYsXG4gICAgICAgIDU5LFxuICAgICAgICAxNzAsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMTA4XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTg0LFxuICAgICAgICAyMTMsXG4gICAgICAgIDk0LFxuICAgICAgICAxNzUsXG4gICAgICAgIDc3LFxuICAgICAgICAxLFxuICAgICAgICAxOTksXG4gICAgICAgIDI4LFxuICAgICAgICAxNDMsXG4gICAgICAgIDE2LFxuICAgICAgICAxNjAsXG4gICAgICAgIDk5LFxuICAgICAgICAxMTAsXG4gICAgICAgIDEsXG4gICAgICAgIDU5LFxuICAgICAgICAyMzcsXG4gICAgICAgIDExOSxcbiAgICAgICAgMTcxLFxuICAgICAgICAyMjMsXG4gICAgICAgIDgzLFxuICAgICAgICAyMTksXG4gICAgICAgIDI3LFxuICAgICAgICAxMTcsXG4gICAgICAgIDIyNCxcbiAgICAgICAgNTUsXG4gICAgICAgIDY2LFxuICAgICAgICA2OSxcbiAgICAgICAgMjQzLFxuICAgICAgICAxOCxcbiAgICAgICAgMTgxLFxuICAgICAgICAxMDBcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDE4OSxcbiAgICAgICAgICA3OCxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDE2MixcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAxMjAsXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDE0MSxcbiAgICAgICAgICA2NixcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDIyMCxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDEzNyxcbiAgICAgICAgICAxNzUsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDk4XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDQzLFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAxMTEsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDEwMCxcbiAgICAgICAgICA5MixcbiAgICAgICAgICA1NixcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxMTcsXG4gICAgICAgICAgMjIwLFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICA0MixcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICA1MixcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgODEsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgNixcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMTY0LFxuICAgICAgICAgIDIwXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTIsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTkzLFxuICAgICAgICA3MCxcbiAgICAgICAgMTA4LFxuICAgICAgICA4MSxcbiAgICAgICAgMjQyLFxuICAgICAgICAyMDMsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTY5LFxuICAgICAgICAxODEsXG4gICAgICAgIDExOCxcbiAgICAgICAgOTMsXG4gICAgICAgIDY3LFxuICAgICAgICAxMSxcbiAgICAgICAgMjMsXG4gICAgICAgIDQ3LFxuICAgICAgICA4MyxcbiAgICAgICAgOTEsXG4gICAgICAgIDcxLFxuICAgICAgICAxODksXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTcxLFxuICAgICAgICA1NyxcbiAgICAgICAgOTUsXG4gICAgICAgIDYyLFxuICAgICAgICAyNTUsXG4gICAgICAgIDk4LFxuICAgICAgICA4NyxcbiAgICAgICAgOTgsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTA2LFxuICAgICAgICAyNyxcbiAgICAgICAgMTYsXG4gICAgICAgIDk5LFxuICAgICAgICAyMTMsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTA5LFxuICAgICAgICAxNSxcbiAgICAgICAgMzQsXG4gICAgICAgIDg5LFxuICAgICAgICA1OCxcbiAgICAgICAgOTEsXG4gICAgICAgIDkyLFxuICAgICAgICAyMyxcbiAgICAgICAgMTk2LFxuICAgICAgICAxMzEsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTQ4LFxuICAgICAgICAxNCxcbiAgICAgICAgMTI2LFxuICAgICAgICAxODAsXG4gICAgICAgIDE2MixcbiAgICAgICAgNDEsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMzYsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTU4LFxuICAgICAgICAxMzUsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTAwLFxuICAgICAgICAxMjUsXG4gICAgICAgIDE4MixcbiAgICAgICAgM1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMzAsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiT1JWYlZ3aGZZTzV2cHhheml4WTZjdE5vTEt3RUJDVzBwSWtoM1h5VUZiUT1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW10sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiV19IN2JJVzhSMUdsdHdsRUFwRTV1UVwiLFxuICBcInBob25lSWRcIjogXCI4MWIyNzQ5Zi04YmU5LTQ1YzktYWY5Yy05OGIyOTRhNGYwZmFcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTc2LFxuICAgICAgNTksXG4gICAgICAxNDIsXG4gICAgICAzMyxcbiAgICAgIDIxNSxcbiAgICAgIDg3LFxuICAgICAgMTA1LFxuICAgICAgNzcsXG4gICAgICAyMCxcbiAgICAgIDIwNyxcbiAgICAgIDE4MSxcbiAgICAgIDE1OCxcbiAgICAgIDQ5LFxuICAgICAgMzMsXG4gICAgICAxMjksXG4gICAgICAxOTcsXG4gICAgICAyNTIsXG4gICAgICAyMzgsXG4gICAgICAxMDcsXG4gICAgICAyNTBcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE1MCxcbiAgICAgIDE2NCxcbiAgICAgIDE3OCxcbiAgICAgIDU2LFxuICAgICAgMTgyLFxuICAgICAgMjIwLFxuICAgICAgMTk1LFxuICAgICAgMTc0LFxuICAgICAgMTgwLFxuICAgICAgMTU4LFxuICAgICAgMTI4LFxuICAgICAgMzUsXG4gICAgICA5NSxcbiAgICAgIDEyNyxcbiAgICAgIDEzMSxcbiAgICAgIDE0MSxcbiAgICAgIDEwMixcbiAgICAgIDgxLFxuICAgICAgMjM0LFxuICAgICAgMTI3XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTnY5b0h3UTdhcWpzZ1lZQVNBQUtBQT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJlY1ozOGxWdFBUVXFWVFZqelZxOUVreGdFNHlIMmNQUCsyZnR6TVVtTzM0PVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcInJHRHdCa3dzYWNqYzJwUmJqdUtPb2dhSDFtcTB1c25GN2E5WW4xdk1LT0FiMEw2UHlMa2YvVVpaT3FJRHdZcjA4SXNpWEw4T2pPQTk4ckpZUzFiTUF3PT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcInFTY1JyQkFRVlNmUTV1UzJ1SGw4RkQ1am9qNE5rUmFWNmVic1gxQ21QQjMwZmlnbGFDRG5oZzJEZGdVak4xZWhJVXlxakhXaTMwQ2JCTGw1cWo5Y0JRPT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0OTE2MDg4NTgzNjoxMkBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMjcyNzU2MjA5OTE4MTA5OjEyQGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIlNpbcO4biBEY1wiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0OTE2MDg4NTgzNjoxMkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgNjEsXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgNDIsXG4gICAgICAgICAgODUsXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDkwLFxuICAgICAgICAgIDE4OSxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICA3NixcbiAgICAgICAgICA5NixcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgMjA3LFxuICAgICAgICAgIDI1MSxcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICAxOTcsXG4gICAgICAgICAgMzgsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMTI2XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MTYwNDkyNjQsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFORE9cIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU5ETy5qc29uIjogIntcImtleURhdGFcIjpcIkJuOS9mdFJSNllvUHB6VEFDbGdoZEVQWk5ETFhJSGIyUGQvQ3hrZFE3ZHM9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjYwNTg3MjIwLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFORFAuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ1UXZqaDIxc0h5alVpUG9zM09mL0lmdFAwK2tWMDlQMjBHQmNjNUY5RjYwPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjI2MDU4NzIyMSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTkRRLmpzb24iOiAie1wia2V5RGF0YVwiOlwidWNlODZhQnVka3BEUlRYWVg2VWpHaklITUV0a01VdjlnalFENllJSk0yOD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyNjA1ODcyMjIsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcxNTA3NTQzODMzM1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU5EUi5qc29uIjogIntcImtleURhdGFcIjpcIlFzODh6S21KSGxlYlluekVUdzBpdkhWOG1FQ1N0bEE1d0NSaVZUOFRjRFU9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjYwNTg3MjIyLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMF19LFwidGltZXN0YW1wXCI6XCIxNzE1MDc1NDcwMjMzXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTkRTLmpzb24iOiAie1wia2V5RGF0YVwiOlwiS2RjQjJDSUxqckhGdzZCeXp5TDk0ZXFPZDlJL1NlQ2IrVDcweE9TcXlPUT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyNjA1ODcyMjMsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU5EVC5qc29uIjogIntcImtleURhdGFcIjpcIlRnYzk3aDhuQmxhTC80WWthVk4vRjJCbnVtQjhWQVJyODZEWG50dldCTFk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjYwNTg3MjIzLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMF19LFwidGltZXN0YW1wXCI6XCIxNzE1MTU4ODY4NzIxXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTkRVLmpzb24iOiAie1wia2V5RGF0YVwiOlwiczZqeFZPYk1QSU1qU1VNMmdHU0lyYktKYWdvWE1uYnVFZ2VacHFpN09oVT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyNjA1ODcyMjQsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU5EVi5qc29uIjogIntcImtleURhdGFcIjpcImxOaWRTS0srQkh3bm1Rb2ZPNzJ3blpWa3JRK0Z3eExFZlNkVUFnanlQYmc9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjYwNTg3MjI1LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFORFcuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJCL3djUmVTbS9KMmZHdG1tS0ZZaWltdXk1aTBwQ3ZxTzd2VWhqcFFoNms0PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjI2MDU4NzIyNixcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9Igp9"  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.6",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
